/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ec.com.kodice.rapipercha.tomafisica.presentacion;

import ec.com.kodice.rapipercha.administracion.negocio.UsuarioBO;
import ec.com.kodice.rapipercha.tomafisica.negocio.OrdenBO;
import ec.com.kodice.rapipercha.administracion.persistencia.EmpleadoVO;
import ec.com.kodice.rapipercha.administracion.persistencia.ProveedorVO;
import ec.com.kodice.rapipercha.util.UtilPresentacion;
import java.time.LocalDate;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * Esta clase contiene atributos y métodos del formulario FrmPerfilAdministracion
 * @author Benjamin Cepeda
 * @version v1.0
 * @date 2020/12/06
 */
public class FrmOrdenListado extends JFrame {
    private EmpleadoVO empleadoLogueado= null;
    private ProveedorVO proveedorEmpleadoLogueado = null;

    /** Creates new form FrmPerfilAdministracion */
    public FrmOrdenListado() {
        initComponents();
        dtpFecha.setDateToToday();
        cargarModelo(dtpFecha.getDate());
        this.setLocationRelativeTo(null);
    }
    public FrmOrdenListado(EmpleadoVO empleadoLogueado, 
            ProveedorVO proveedorEmpleadoLoguedo) {
        this.empleadoLogueado = empleadoLogueado;
        this.proveedorEmpleadoLogueado = proveedorEmpleadoLoguedo;
        initComponents();
        dtpFecha.setDateToToday();
        this.lblNombreEmpresa.setText(proveedorEmpleadoLogueado.getNombreComercial()
            + " - "+ proveedorEmpleadoLogueado.getRazonSocial());
        this.lblNombreEmpleado.setText(empleadoLogueado.getNombres() + " " +
                empleadoLogueado.getApellidos());        
        cargarModelo(dtpFecha.getDate());
        this.setLocationRelativeTo(null);
    }

    private void cargarModelo(LocalDate fecha){        
        OrdenBO ordenBO = new OrdenBO();        
        try {
            tblOrdenes.setModel(ordenBO.generaModeloDatosTabla( 
                empleadoLogueado.getUsuario().getCodigo(), fecha,
                new Object[]{
                    "CODIGO", "A REALIZAR", "RAZON SOCIAL", "LOCAL", "DIRECCION",
                    "GENERADO POR", "GENERADA EN","ESTADO"}));
        }
        catch ( Exception e) {
            UtilPresentacion.mostrarMensajeError(this, e.getMessage());
        }
        finally{
            ordenBO = null;   
            btnConsultar.setEnabled(false);
            btnTomaFisica.setEnabled(false);
            btnCerrarOrden.setEnabled(false);
        }
            
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenedor = new javax.swing.JPanel();
        pnlCabecera = new javax.swing.JPanel();
        lblLogoRapipercha = new javax.swing.JLabel();
        lblTituloOrden = new javax.swing.JLabel();
        lblNombreEmpleado = new javax.swing.JLabel();
        lblTituloEmpresa = new javax.swing.JLabel();
        lblNombreEmpresa = new javax.swing.JLabel();
        pnlDetalle = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrdenes = new javax.swing.JTable();
        pnlPie = new javax.swing.JPanel();
        btnConsultar = new javax.swing.JButton();
        btnTomaFisica = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblLogoKodice = new javax.swing.JLabel();
        btnCerrarOrden = new javax.swing.JButton();
        dtpFecha = new com.github.lgooddatepicker.components.DatePicker();
        lblFecha = new javax.swing.JLabel();
        btnMostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        pnlContenedor.setAlignmentX(0.0F);
        pnlContenedor.setAlignmentY(0.0F);
        pnlContenedor.setPreferredSize(new java.awt.Dimension(800, 650));

        pnlCabecera.setBackground(new java.awt.Color(64, 124, 202));
        pnlCabecera.setAlignmentX(0.0F);
        pnlCabecera.setAlignmentY(0.0F);
        pnlCabecera.setMaximumSize(new java.awt.Dimension(32767, 90));
        pnlCabecera.setMinimumSize(new java.awt.Dimension(0, 90));
        pnlCabecera.setPreferredSize(new java.awt.Dimension(445, 90));

        lblLogoRapipercha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/kodice/rapipercha/imagenes/logo-rapipercha.png"))); // NOI18N

        lblTituloOrden.setText("ORDENES ASIGNADAS A:");
        lblTituloOrden.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTituloOrden.setForeground(new java.awt.Color(255, 255, 255));

        lblNombreEmpleado.setText("NOMBRE EMPLEADO");
        lblNombreEmpleado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNombreEmpleado.setForeground(new java.awt.Color(255, 255, 255));

        lblTituloEmpresa.setText("EMPRESA:");
        lblTituloEmpresa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTituloEmpresa.setForeground(new java.awt.Color(255, 255, 255));

        lblNombreEmpresa.setText("NOMBRE EMPRESA");
        lblNombreEmpresa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNombreEmpresa.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlCabeceraLayout = new javax.swing.GroupLayout(pnlCabecera);
        pnlCabecera.setLayout(pnlCabeceraLayout);
        pnlCabeceraLayout.setHorizontalGroup(
            pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCabeceraLayout.createSequentialGroup()
                .addComponent(lblLogoRapipercha)
                .addGap(129, 129, 129)
                .addGroup(pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCabeceraLayout.createSequentialGroup()
                        .addComponent(lblTituloOrden)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCabeceraLayout.createSequentialGroup()
                        .addComponent(lblTituloEmpresa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlCabeceraLayout.setVerticalGroup(
            pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogoRapipercha)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCabeceraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloEmpresa)
                    .addComponent(lblNombreEmpresa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloOrden)
                    .addComponent(lblNombreEmpleado))
                .addGap(31, 31, 31))
        );

        pnlDetalle.setAlignmentX(0.0F);
        pnlDetalle.setAlignmentY(0.0F);

        tblOrdenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Codigo", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOrdenes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblOrdenes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblOrdenes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblOrdenesMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblOrdenes);

        pnlPie.setMaximumSize(new java.awt.Dimension(32767, 90));
        pnlPie.setMinimumSize(new java.awt.Dimension(0, 90));
        pnlPie.setPreferredSize(new java.awt.Dimension(780, 90));

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/kodice/rapipercha/imagenes/Zoom.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.setAlignmentY(0.0F);
        btnConsultar.setBackground(new java.awt.Color(64, 124, 202));
        btnConsultar.setBorderPainted(false);
        btnConsultar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnConsultar.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultar.setIconTextGap(1);
        btnConsultar.setMaximumSize(new java.awt.Dimension(135, 55));
        btnConsultar.setMinimumSize(new java.awt.Dimension(135, 55));
        btnConsultar.setPreferredSize(new java.awt.Dimension(135, 55));
        btnConsultar.setToolTipText("");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnTomaFisica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/kodice/rapipercha/imagenes/Clipboard b.png"))); // NOI18N
        btnTomaFisica.setText("Toma Física");
        btnTomaFisica.setAlignmentY(0.0F);
        btnTomaFisica.setBackground(new java.awt.Color(64, 124, 202));
        btnTomaFisica.setBorderPainted(false);
        btnTomaFisica.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTomaFisica.setForeground(new java.awt.Color(255, 255, 255));
        btnTomaFisica.setIconTextGap(1);
        btnTomaFisica.setMaximumSize(new java.awt.Dimension(118, 55));
        btnTomaFisica.setMinimumSize(new java.awt.Dimension(118, 55));
        btnTomaFisica.setPreferredSize(new java.awt.Dimension(118, 55));
        btnTomaFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTomaFisicaActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/kodice/rapipercha/imagenes/Badge-cancel.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setAlignmentY(0.0F);
        btnSalir.setBackground(new java.awt.Color(64, 124, 202));
        btnSalir.setBorderPainted(false);
        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setIconTextGap(1);
        btnSalir.setMaximumSize(new java.awt.Dimension(118, 55));
        btnSalir.setMinimumSize(new java.awt.Dimension(118, 55));
        btnSalir.setPreferredSize(new java.awt.Dimension(118, 55));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        lblLogoKodice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/kodice/rapipercha/imagenes/logo-kodice.png"))); // NOI18N
        lblLogoKodice.setMaximumSize(new java.awt.Dimension(125, 55));
        lblLogoKodice.setMinimumSize(new java.awt.Dimension(125, 55));
        lblLogoKodice.setPreferredSize(new java.awt.Dimension(125, 55));

        btnCerrarOrden.setBackground(new java.awt.Color(64, 124, 202));
        btnCerrarOrden.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCerrarOrden.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarOrden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/kodice/rapipercha/imagenes/Folder docs.png"))); // NOI18N
        btnCerrarOrden.setText("Cerrar Orden");
        btnCerrarOrden.setAlignmentY(0.0F);
        btnCerrarOrden.setBorderPainted(false);
        btnCerrarOrden.setIconTextGap(1);
        btnCerrarOrden.setMaximumSize(new java.awt.Dimension(118, 55));
        btnCerrarOrden.setMinimumSize(new java.awt.Dimension(118, 55));
        btnCerrarOrden.setPreferredSize(new java.awt.Dimension(118, 55));
        btnCerrarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarOrdenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPieLayout = new javax.swing.GroupLayout(pnlPie);
        pnlPie.setLayout(pnlPieLayout);
        pnlPieLayout.setHorizontalGroup(
            pnlPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPieLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTomaFisica, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(lblLogoKodice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        pnlPieLayout.setVerticalGroup(
            pnlPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogoKodice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTomaFisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCerrarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        lblFecha.setText("Fecha a realizar:");

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDetalleLayout = new javax.swing.GroupLayout(pnlDetalle);
        pnlDetalle.setLayout(pnlDetalleLayout);
        pnlDetalleLayout.setHorizontalGroup(
            pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(pnlPie, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(pnlDetalleLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblFecha)
                .addGap(47, 47, 47)
                .addComponent(dtpFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMostrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDetalleLayout.setVerticalGroup(
            pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dtpFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFecha)
                    .addComponent(btnMostrar))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlContenedorLayout = new javax.swing.GroupLayout(pnlContenedor);
        pnlContenedor.setLayout(pnlContenedorLayout);
        pnlContenedorLayout.setHorizontalGroup(
            pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCabecera, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addComponent(pnlDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlContenedorLayout.setVerticalGroup(
            pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenedorLayout.createSequentialGroup()
                .addComponent(pnlCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnTomaFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTomaFisicaActionPerformed
        String codigoElegido = "";
        String nombreCentroExpendio="";
        String nombreLocal="";
        int fila = tblOrdenes.getSelectedRow();
        if (fila >= 0) {
            codigoElegido = tblOrdenes.getModel().getValueAt(
                    fila, 0).toString();
            nombreCentroExpendio = tblOrdenes.getModel().getValueAt(
                    fila, 2).toString();
            nombreLocal = tblOrdenes.getModel().getValueAt(
                    fila, 3).toString();            
        }
        if (!(codigoElegido.isEmpty() | codigoElegido.isBlank())) {
            FrmDetalleOrdenListado frmDetalleOrdenListado = new 
            FrmDetalleOrdenListado(
                    empleadoLogueado,proveedorEmpleadoLogueado,
                    Integer.valueOf(codigoElegido), 
                    nombreCentroExpendio, nombreLocal,
                    false);
            frmDetalleOrdenListado.setVisible(true);
            cargarModelo(dtpFecha.getDate());
        }
    }//GEN-LAST:event_btnTomaFisicaActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        String codigoElegido = "";
        String nombreCentroExpendio="";
        String nombreLocal="";
        int fila = tblOrdenes.getSelectedRow();
        if (fila >= 0) {
            codigoElegido = tblOrdenes.getModel().getValueAt(
                    fila, 0).toString();
            nombreCentroExpendio = tblOrdenes.getModel().getValueAt(
                    fila, 2).toString();
            nombreLocal = tblOrdenes.getModel().getValueAt(
                    fila, 3).toString();            
        }
        if (!(codigoElegido.isEmpty() | codigoElegido.isBlank())) {
            FrmDetalleOrdenListado frmDetalleOrdenListado = new 
            FrmDetalleOrdenListado(
                empleadoLogueado,proveedorEmpleadoLogueado,
                Integer.valueOf(codigoElegido), 
                nombreCentroExpendio, nombreLocal,
                true);
            frmDetalleOrdenListado.setVisible(true);
            cargarModelo(dtpFecha.getDate());
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void tblOrdenesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOrdenesMousePressed
        JTable source = (JTable) evt.getSource();
        String codigoElegido = "";
        String nombreCentroExpendio="";
        String nombreLocal="";
        String estadoOrden;
        int fila = source.rowAtPoint(evt.getPoint());
        //int column = source.columnAtPoint(evt.getPoint());
        if (fila >= 0) {
            codigoElegido = tblOrdenes.getModel().getValueAt(
                    fila, 0).toString();
            nombreCentroExpendio = tblOrdenes.getModel().getValueAt(
                    fila, 2).toString();
            nombreLocal = tblOrdenes.getModel().getValueAt(
                    fila, 3).toString();            
            estadoOrden  = tblOrdenes.getModel().getValueAt(
                    fila, 7).toString();            
            btnConsultar.setEnabled(true);
            if (estadoOrden.equalsIgnoreCase("ACTIVA")){
                btnTomaFisica.setEnabled(true);
                btnCerrarOrden.setEnabled(true);
            }
            else{
                btnTomaFisica.setEnabled(false);
                btnCerrarOrden.setEnabled(false);
            }
            if (evt.getClickCount() == 2 && !codigoElegido.isEmpty() && !codigoElegido.isBlank()) {
                FrmDetalleOrdenListado frmDetalleOrdenListado = new 
                FrmDetalleOrdenListado(
                    empleadoLogueado,proveedorEmpleadoLogueado,
                    Integer.valueOf(codigoElegido),
                    nombreCentroExpendio, nombreLocal,
                    true);
                frmDetalleOrdenListado.setVisible(true);
                cargarModelo(dtpFecha.getDate());
            }
        }
    }//GEN-LAST:event_tblOrdenesMousePressed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        cargarModelo(dtpFecha.getDate());
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnCerrarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarOrdenActionPerformed
        String codigoElegido = "";
        String nombreCentroExpendio="";
        String nombreLocal="";
        String estadoOrden;

        boolean confirmacion = false;
        int fila = tblOrdenes.getSelectedRow();
        if (fila >= 0) {
            codigoElegido = tblOrdenes.getModel().getValueAt(
                    fila, 0).toString();
            nombreCentroExpendio = tblOrdenes.getModel().getValueAt(
                    fila, 2).toString();
            nombreLocal = tblOrdenes.getModel().getValueAt(
                    fila, 3).toString();            
            estadoOrden  = tblOrdenes.getModel().getValueAt(
                    fila, 7).toString();            
        }
        if (!(codigoElegido.isEmpty() | codigoElegido.isBlank())) {
            confirmacion = (UtilPresentacion.mostrarMensajeConfirmacion(
                    this, "Desea Cerrar la Orden:\n" + codigoElegido + " - "
                    + nombreCentroExpendio + " - " + nombreLocal)
                    == JOptionPane.YES_OPTION);
            if (confirmacion) {
                OrdenBO ordenBO = new OrdenBO();
                try {
                    ordenBO.cerrarOrden(Integer.valueOf(codigoElegido));
                } catch (Exception e) {
                    UtilPresentacion.mostrarMensajeError(this, e.getMessage());
                } finally {
                    ordenBO = null;
                }
            }
            cargarModelo(dtpFecha.getDate());
        }

    }//GEN-LAST:event_btnCerrarOrdenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmOrdenListado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmOrdenListado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmOrdenListado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmOrdenListado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmOrdenListado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarOrden;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnTomaFisica;
    private com.github.lgooddatepicker.components.DatePicker dtpFecha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblLogoKodice;
    private javax.swing.JLabel lblLogoRapipercha;
    private javax.swing.JLabel lblNombreEmpleado;
    private javax.swing.JLabel lblNombreEmpresa;
    private javax.swing.JLabel lblTituloEmpresa;
    private javax.swing.JLabel lblTituloOrden;
    private javax.swing.JPanel pnlCabecera;
    private javax.swing.JPanel pnlContenedor;
    private javax.swing.JPanel pnlDetalle;
    private javax.swing.JPanel pnlPie;
    private javax.swing.JTable tblOrdenes;
    // End of variables declaration//GEN-END:variables

}
