/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ec.com.kodice.rapipercha.tomafisica.presentacion;
import ec.com.kodice.rapipercha.administracion.negocio.ProveedorBO;
import ec.com.kodice.rapipercha.administracion.persistencia.ProveedorVO;
import ec.com.kodice.rapipercha.tomafisica.negocio.DetalleOrdenBO;
import ec.com.kodice.rapipercha.tomafisica.persistencia.DetalleOrdenVO;
import ec.com.kodice.rapipercha.util.UtilPresentacion;
import javax.swing.JOptionPane;

/**
 *
 * Esta clase contiene atributos y métodos para el registro de Toma Física
 * @author Benjamin Cepeda
 * @version v1.0
 * @date 2021/01/17
 */
public class FrmRegistroTomaFisica extends javax.swing.JDialog {
    private int codigoActual = 0;

    public void setCodigoActual(int codigoActual) {
        this.codigoActual = codigoActual;
    }

    public FrmRegistroTomaFisica(int codigoActual, boolean soloLectura) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.codigoActual = codigoActual;
        if (soloLectura)
            seteaControles(soloLectura);
        cargarDatos();
    }
    
    public FrmRegistroTomaFisica() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.codigoActual = 0;
        cargarDatos();
    }
    private void seteaControles(boolean soloLectura){
        btnGrabar.setEnabled(!soloLectura);
    }
    
    private void cargarDatos(){
        DetalleOrdenVO detalleOrdenVO = null;
        DetalleOrdenBO detalleOrdenBO = new DetalleOrdenBO();
        try {
            if (codigoActual!=0){
                detalleOrdenVO=detalleOrdenBO.buscar(codigoActual);
            }
        }
        catch ( Exception e) {
            UtilPresentacion.mostrarMensajeError(this, e.getMessage());
        }
        finally{
            if (detalleOrdenVO != null){
                txtCodigo.setText(String.valueOf(detalleOrdenVO.getCodigo()));
                txtOrdenCodigo.setText(String.valueOf(detalleOrdenVO.getOrdenCodigo()));
                txtProductoDescripcion.setText(detalleOrdenVO.getProducto().getDescripcion());
                txtCantidadMinima.setText(String.valueOf(detalleOrdenVO.getCantidadMinima()));
                txtExistencia.setText(String.valueOf(detalleOrdenVO.getExistencia()));
                txtCantidadRevisada.setText(String.valueOf(detalleOrdenVO.getCantidadRevisada()));
                txtCantidadMalEstado.setText(String.valueOf(detalleOrdenVO.getCantidadMalEstado()));
                txtCantidadVencido.setText(String.valueOf(detalleOrdenVO.getCantidadVencido()));
                if (detalleOrdenVO.getFechaProceso()!=null)
                    txtFechaProceso.setText(detalleOrdenVO.getFechaProceso().toString());
            }
            detalleOrdenVO = null;
            detalleOrdenBO = null;
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenedor = new javax.swing.JPanel();
        pnlCabecera = new javax.swing.JPanel();
        lblLogoRapipercha = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        pnlDetalle = new javax.swing.JPanel();
        lblOrdenCodigo = new javax.swing.JLabel();
        txtOrdenCodigo = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblProducto = new javax.swing.JLabel();
        txtProductoDescripcion = new javax.swing.JTextField();
        lblCantidadMinima = new javax.swing.JLabel();
        txtCantidadMinima = new javax.swing.JTextField();
        lblExistencia = new javax.swing.JLabel();
        txtExistencia = new javax.swing.JTextField();
        lblCantidadRevisada = new javax.swing.JLabel();
        txtCantidadRevisada = new javax.swing.JTextField();
        lblCantidadMalEstado = new javax.swing.JLabel();
        txtCantidadMalEstado = new javax.swing.JTextField();
        lblCantidadVencido = new javax.swing.JLabel();
        txtCantidadVencido = new javax.swing.JTextField();
        lblFechaProceso = new javax.swing.JLabel();
        txtFechaProceso = new javax.swing.JTextField();
        pnlPie = new javax.swing.JPanel();
        btnGrabar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblLogoKodice = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setResizable(false);

        pnlContenedor.setAlignmentX(0.0F);
        pnlContenedor.setAlignmentY(0.0F);
        pnlContenedor.setPreferredSize(new java.awt.Dimension(800, 600));

        pnlCabecera.setBackground(new java.awt.Color(64, 124, 202));
        pnlCabecera.setAlignmentX(0.0F);
        pnlCabecera.setAlignmentY(0.0F);
        pnlCabecera.setMaximumSize(new java.awt.Dimension(32767, 90));
        pnlCabecera.setMinimumSize(new java.awt.Dimension(0, 90));
        pnlCabecera.setPreferredSize(new java.awt.Dimension(518, 90));

        lblLogoRapipercha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/kodice/rapipercha/imagenes/logo-rapipercha.png"))); // NOI18N

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("REGISTRO DE TOMA FISICA");

        javax.swing.GroupLayout pnlCabeceraLayout = new javax.swing.GroupLayout(pnlCabecera);
        pnlCabecera.setLayout(pnlCabeceraLayout);
        pnlCabeceraLayout.setHorizontalGroup(
            pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCabeceraLayout.createSequentialGroup()
                .addComponent(lblLogoRapipercha)
                .addGap(202, 202, 202)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlCabeceraLayout.setVerticalGroup(
            pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogoRapipercha)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCabeceraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(30, 30, 30))
        );

        pnlDetalle.setAlignmentX(0.0F);
        pnlDetalle.setAlignmentY(0.0F);

        lblOrdenCodigo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblOrdenCodigo.setText("Orden No:");

        txtOrdenCodigo.setEnabled(false);
        txtOrdenCodigo.setMinimumSize(new java.awt.Dimension(7, 22));
        txtOrdenCodigo.setPreferredSize(new java.awt.Dimension(7, 22));

        lblCodigo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCodigo.setText("Código:");

        txtCodigo.setEnabled(false);
        txtCodigo.setMinimumSize(new java.awt.Dimension(7, 22));
        txtCodigo.setPreferredSize(new java.awt.Dimension(7, 22));

        lblProducto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblProducto.setText("Producto:");

        txtProductoDescripcion.setEnabled(false);
        txtProductoDescripcion.setMinimumSize(new java.awt.Dimension(7, 22));
        txtProductoDescripcion.setPreferredSize(new java.awt.Dimension(7, 22));

        lblCantidadMinima.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCantidadMinima.setText("Cantidad Minima:");

        txtCantidadMinima.setEnabled(false);
        txtCantidadMinima.setMinimumSize(new java.awt.Dimension(7, 22));
        txtCantidadMinima.setPreferredSize(new java.awt.Dimension(7, 22));

        lblExistencia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblExistencia.setText("Existencia:");

        txtExistencia.setEnabled(false);
        txtExistencia.setMinimumSize(new java.awt.Dimension(7, 22));
        txtExistencia.setPreferredSize(new java.awt.Dimension(7, 22));

        lblCantidadRevisada.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCantidadRevisada.setText("Cantidad Revisada:");

        txtCantidadRevisada.setMinimumSize(new java.awt.Dimension(7, 22));
        txtCantidadRevisada.setPreferredSize(new java.awt.Dimension(7, 22));

        lblCantidadMalEstado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCantidadMalEstado.setText("Cantidad Mal Estado:");

        txtCantidadMalEstado.setMinimumSize(new java.awt.Dimension(7, 22));
        txtCantidadMalEstado.setPreferredSize(new java.awt.Dimension(7, 22));

        lblCantidadVencido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCantidadVencido.setText("Cantidad Vencido:");

        txtCantidadVencido.setMinimumSize(new java.awt.Dimension(7, 22));
        txtCantidadVencido.setPreferredSize(new java.awt.Dimension(7, 22));

        lblFechaProceso.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblFechaProceso.setText("Fecha proceso:");

        txtFechaProceso.setEnabled(false);
        txtFechaProceso.setMinimumSize(new java.awt.Dimension(7, 22));
        txtFechaProceso.setPreferredSize(new java.awt.Dimension(7, 22));

        javax.swing.GroupLayout pnlDetalleLayout = new javax.swing.GroupLayout(pnlDetalle);
        pnlDetalle.setLayout(pnlDetalleLayout);
        pnlDetalleLayout.setHorizontalGroup(
            pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalleLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlDetalleLayout.createSequentialGroup()
                        .addComponent(lblOrdenCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtOrdenCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDetalleLayout.createSequentialGroup()
                        .addComponent(lblCantidadMalEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCantidadMalEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDetalleLayout.createSequentialGroup()
                        .addComponent(lblProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtProductoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDetalleLayout.createSequentialGroup()
                        .addComponent(lblCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDetalleLayout.createSequentialGroup()
                        .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCantidadRevisada)
                            .addComponent(lblCantidadMinima)
                            .addComponent(lblExistencia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCantidadMinima, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtExistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidadRevisada, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDetalleLayout.createSequentialGroup()
                            .addComponent(lblFechaProceso)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtFechaProceso, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlDetalleLayout.createSequentialGroup()
                            .addComponent(lblCantidadVencido)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtCantidadVencido, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        pnlDetalleLayout.setVerticalGroup(
            pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalleLayout.createSequentialGroup()
                .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblOrdenCodigo)
                    .addComponent(txtOrdenCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlDetalleLayout.createSequentialGroup()
                        .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtProductoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProducto))
                        .addGap(16, 16, 16)
                        .addComponent(lblCantidadMinima))
                    .addComponent(txtCantidadMinima, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblExistencia)
                    .addComponent(txtExistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCantidadRevisada)
                    .addComponent(txtCantidadRevisada, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCantidadMalEstado)
                    .addComponent(txtCantidadMalEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCantidadVencido)
                    .addComponent(txtCantidadVencido, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaProceso, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaProceso))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pnlPie.setMaximumSize(new java.awt.Dimension(32767, 90));
        pnlPie.setMinimumSize(new java.awt.Dimension(0, 90));
        pnlPie.setPreferredSize(new java.awt.Dimension(780, 90));

        btnGrabar.setBackground(new java.awt.Color(64, 124, 202));
        btnGrabar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnGrabar.setForeground(new java.awt.Color(255, 255, 255));
        btnGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/kodice/rapipercha/imagenes/Disquette.png"))); // NOI18N
        btnGrabar.setText("Grabar");
        btnGrabar.setToolTipText("");
        btnGrabar.setAlignmentY(0.0F);
        btnGrabar.setBorderPainted(false);
        btnGrabar.setPreferredSize(new java.awt.Dimension(125, 57));
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(64, 124, 202));
        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/kodice/rapipercha/imagenes/Badge-cancel.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setAlignmentY(0.0F);
        btnSalir.setBorderPainted(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        lblLogoKodice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/kodice/rapipercha/imagenes/logo-kodice.png"))); // NOI18N

        javax.swing.GroupLayout pnlPieLayout = new javax.swing.GroupLayout(pnlPie);
        pnlPie.setLayout(pnlPieLayout);
        pnlPieLayout.setHorizontalGroup(
            pnlPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPieLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 363, Short.MAX_VALUE)
                .addComponent(lblLogoKodice)
                .addGap(48, 48, 48))
        );
        pnlPieLayout.setVerticalGroup(
            pnlPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogoKodice, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSalir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlContenedorLayout = new javax.swing.GroupLayout(pnlContenedor);
        pnlContenedor.setLayout(pnlContenedorLayout);
        pnlContenedorLayout.setHorizontalGroup(
            pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCabecera, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addComponent(pnlDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlPie, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        pnlContenedorLayout.setVerticalGroup(
            pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenedorLayout.createSequentialGroup()
                .addComponent(pnlCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlPie, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 454, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
        DetalleOrdenVO detalleOrdenVO = null;
        DetalleOrdenBO detalleOrdenBO = null;
        int respuestaOperacion = 0;
        boolean camposValidos;
        camposValidos = (           
                !txtCantidadRevisada.getText().isEmpty() && 
                !txtCantidadRevisada.getText().trim().equals("") &&                 
                !txtCantidadMalEstado.getText().isEmpty() && 
                !txtCantidadMalEstado.getText().trim().equals("") &&                 
                !txtCantidadVencido.getText().isEmpty() && 
                !txtCantidadVencido.getText().trim().equals("")                 
                );                
        if (camposValidos){
            camposValidos = Float.parseFloat(txtCantidadRevisada.getText())>=0 &&
                    Float.parseFloat(txtCantidadRevisada.getText())<=
                    Float.parseFloat(txtExistencia.getText()) &&
                    (Float.parseFloat(txtCantidadMalEstado.getText()) +
                    Float.parseFloat(txtCantidadVencido.getText())) <=
                    Float.parseFloat(txtCantidadRevisada.getText());
            if (camposValidos){
                detalleOrdenBO = new DetalleOrdenBO();
                detalleOrdenVO = new DetalleOrdenVO(
                    codigoActual, 
                    Integer.parseInt(txtOrdenCodigo.getText()),
                    0, 
                    Float.parseFloat(txtCantidadMinima.getText()), 
                    Float.parseFloat(txtExistencia.getText()),
                    Float.parseFloat(txtCantidadRevisada.getText()),
                    Float.parseFloat(txtCantidadMalEstado.getText()),
                    Float.parseFloat(txtCantidadVencido.getText()),
                    null
                );                            
                try{
                    respuestaOperacion = detalleOrdenBO.registrarTomaFisica(detalleOrdenVO);
                    if (respuestaOperacion>0)
                        JOptionPane.showMessageDialog(null, "Registro guardado con éxito");
                }
                catch(Exception e){
                    UtilPresentacion.mostrarMensajeError(this, e.getMessage());
                }
                finally{
                    detalleOrdenVO = null;
                    detalleOrdenBO = null;
                    this.setVisible(false);
                    this.dispose();
                }
            } else{
                UtilPresentacion.mostrarMensajeValidacionIncorrecta(this, 
                "Los valores ingresados no son consistentes");                
            }
        }else {
            UtilPresentacion.mostrarMensajeValidacionIncorrecta(this, 
                "Ingrese los datos requeridos en el formulario");
        }
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistroTomaFisica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistroTomaFisica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistroTomaFisica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistroTomaFisica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegistroTomaFisica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lblCantidadMalEstado;
    private javax.swing.JLabel lblCantidadMinima;
    private javax.swing.JLabel lblCantidadRevisada;
    private javax.swing.JLabel lblCantidadVencido;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblExistencia;
    private javax.swing.JLabel lblFechaProceso;
    private javax.swing.JLabel lblLogoKodice;
    private javax.swing.JLabel lblLogoRapipercha;
    private javax.swing.JLabel lblOrdenCodigo;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlCabecera;
    private javax.swing.JPanel pnlContenedor;
    private javax.swing.JPanel pnlDetalle;
    private javax.swing.JPanel pnlPie;
    private javax.swing.JTextField txtCantidadMalEstado;
    private javax.swing.JTextField txtCantidadMinima;
    private javax.swing.JTextField txtCantidadRevisada;
    private javax.swing.JTextField txtCantidadVencido;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtExistencia;
    private javax.swing.JTextField txtFechaProceso;
    private javax.swing.JTextField txtOrdenCodigo;
    private javax.swing.JTextField txtProductoDescripcion;
    // End of variables declaration//GEN-END:variables

}
